name: Build and Deploy Telegram Bot

on:
  push:
    branches: [ "main" ] # Запускать при пуше в ветку main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
        build-args: |
          BOT_TOKEN=${{ secrets.BOT_TOKEN }}

  deploy:
    needs: build-and-push # Запускать только после успешной сборки
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /opt/telegram-bot # Путь, где вы склонировали репозиторий
          docker pull ghcr.io/${{ github.repository }}:latest
          docker-compose up -d
